# Generated by Django 4.2.6 on 2023-10-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('filedata', models.FileField(upload_to='shop')),
                ('filetype', models.CharField(choices=[('image', 'image'), ('video', 'video'), ('audio', 'audio'), ('text', 'text'), ('others', 'others')], max_length=6)),
                ('filedesc', models.CharField(max_length=300)),
                ('date_added', models.DateField()),
            ],
        ),
    ]
