# Generated by Django 4.2.6 on 2023-10-20 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filedata',
            old_name='filedata',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='filedata',
            old_name='filedesc',
            new_name='File_description',
        ),
        migrations.RenameField(
            model_name='filedata',
            old_name='filetype',
            new_name='File_type',
        ),
        migrations.RenameField(
            model_name='filedata',
            old_name='title',
            new_name='Title',
        ),
    ]
